# Generated by Django 5.0.4 on 2024-06-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='perfil/default.jpg', upload_to='perfil/'),
        ),
    ]
